# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccintor', '0002_auto_20160910_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patients', related_query_name='patient', to='vaccintor.Doctor'),
        ),
    ]
