# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccintor', '0003_auto_20160910_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
