# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccintor', '0004_auto_20160910_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('needed_before_registration', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccintor.Child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccintor.Vaccine')),
            ],
        ),
    ]
